// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmz6NSFUSvgkhBo4JEy5X-p98OLWjRqwQ',
    appId: '1:1028437984243:web:919357727bd4fc812c0886',
    messagingSenderId: '1028437984243',
    projectId: 'flutter-login-app-f9be8',
    authDomain: 'flutter-login-app-f9be8.firebaseapp.com',
    storageBucket: 'flutter-login-app-f9be8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArqccmWtBZWEsitcCd1s1BZBml6748a1c',
    appId: '1:1028437984243:android:6072633fe56717f42c0886',
    messagingSenderId: '1028437984243',
    projectId: 'flutter-login-app-f9be8',
    storageBucket: 'flutter-login-app-f9be8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAabKjAwZqD_E0uVpCuHo1yBOPZlIOs7Hk',
    appId: '1:1028437984243:ios:ee702f3e6e6a93c32c0886',
    messagingSenderId: '1028437984243',
    projectId: 'flutter-login-app-f9be8',
    storageBucket: 'flutter-login-app-f9be8.appspot.com',
    iosBundleId: 'com.example.ruralEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAabKjAwZqD_E0uVpCuHo1yBOPZlIOs7Hk',
    appId: '1:1028437984243:ios:ee604daf6c1e90672c0886',
    messagingSenderId: '1028437984243',
    projectId: 'flutter-login-app-f9be8',
    storageBucket: 'flutter-login-app-f9be8.appspot.com',
    iosBundleId: 'com.example.ruralEducation.RunnerTests',
  );
}
